package exception;

class Test6 {
	
	// 현재 메서드 내부에서 발생하는 NullPointerException을 caller에게 전가시킨다
	void method1() throws NullPointerException{
		String str = null;
		System.out.println(str.charAt(0));
	}
	
	void method2() throws ArrayIndexOutOfBoundsException{
		int[] arr = {2, 7, 8, 4, 6};
		System.out.println(arr[5]);
	}
}

public class Ex06 {
	public static void main(String[] args) throws Exception{
		// throws : 현재 함수에서 발생한 예외의 처리를 caller에게 전가시킨다
		
		Test6 ob = new Test6();
		try {
//		ob.method1();
		ob.method2();
		} catch(NullPointerException e) {
			System.out.println("null값에 대한 메서드를 호출할 수 없습니다.");
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("배열의 인덱스는 길이보다 작아야 합니다");
		}
	}

}
